-- Scale mode (PokéSize): daily 5 height-comparison pairs
do $$ begin
  create type public.scale_game_status as enum ('PLAYING', 'COMPLETE');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.scale_challenges (
  id integer primary key,
  date date not null,
  pairs_json jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists scale_challenges_date_idx
  on public.scale_challenges (date);

create table if not exists public.scale_games (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  challenge_id integer not null references public.scale_challenges (id),
  status public.scale_game_status not null,
  rounds_json jsonb not null default '[]'::jsonb,
  total_score integer not null default 0,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists scale_games_user_challenge_idx
  on public.scale_games (user_id, challenge_id);
